api_version: 1
application: techism2
default_expiration: 1d
handlers:
- {login: admin, script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py, url: /remote_api}
- {login: admin, script: djangoappengine/deferred/handler.py, url: /_ah/queue/deferred}
- {expiration: 1d, static_dir: django/contrib/admin/media/, url: /media/admin}
- {static_files: static/favicon.ico, upload: static/favicon.ico, url: /favicon.ico}
- {static_files: static/robots.txt, upload: static/robots.txt, url: /robots.txt}
- {static_files: static/loader.gif, upload: static/loader.gif, url: /loader.gif}
- {static_files: static/google6aef877ff1ed9813.html, upload: static/google6aef877ff1ed9813.html,
  url: /google6aef877ff1ed9813.html}
- {expiration: 365d, static_dir: _generated_media/, url: /media}
- {script: djangoappengine/main/main.py, url: /.*}
runtime: python
version: '15'
